export class User {
  id: number;
  nome: string;
  cognome: string;
  azienda: string;
  collaboratore: string;
  collaboratore1: string;
  tipoContatto: string;
  tipoContatto2: string;
  telCasa: string;
  telUfficio: string;
  email: string;
  secondaEmail: string;
  fax: string;
  PEC: string;
  indirizzoResidenza: string;
  civico: string;
  occupazione: string;
  dataNascita:string;
  codiceFiscale: string;
  cartaIdentita: string;
  dataScadenzaCartaIdentita: string;
  partitaIva:string;
  sdi: string;
  iban: string;
  hobby:string;
  note: string;
  comune: string;
  provincia: string;
  CAP: string;
  datiAggiuntivi: string;
  datiRaw: string;
}